[package]
name = "sol-contract-prac"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh-derive = "1.5.6"
solana-program = "2.2.1"
borsh= {version = "1.5.6", features = ["derive"]}